from flask import Flask, request, jsonify
from dotenv import load_dotenv
import os
import uuid
from datetime import datetime
from signals.llm_classifier import classify_with_llm
from signals.stylometric import calculate_stylometric_score
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# Simple in-memory audit log
audit_log = []

def get_attribution(score: float) -> str:
    if score > 0.75:
        return "likely_ai"
    elif score > 0.45:
        return "uncertain"
    else:
        return "likely_human"

def combine_signals(llm_score: float, stylo_score: float) -> float:
    return round((llm_score * 0.6) + (stylo_score * 0.4), 3)

def get_label(attribution: str) -> str:
    if attribution == "likely_ai":
        return "This content appears to be AI-generated. If you believe this is incorrect, you may submit an appeal."
    elif attribution == "uncertain":
        return "This content shows mixed signals. We were unable to determine with confidence whether it was written by a human or generated by AI. If you believe this is incorrect, you may submit an appeal."
    else:
        return "This content appears to be written by a human."

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text and creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    # Run both signals
    llm_score = classify_with_llm(text)
    stylo_score = calculate_stylometric_score(text)

    # Combine into final confidence score
    confidence = combine_signals(llm_score, stylo_score)
    attribution = get_attribution(confidence)
    label = get_label(attribution)

    # Log the entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "confidence": confidence,
        "attribution": attribution,
        "label": label,
        "status": "classified",
        "appeal": None
    }
    audit_log.append(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label": label
    })

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id and creator_reasoning"}), 400

    content_id = data["content_id"]
    creator_reasoning = data["creator_reasoning"]

    # Find the original submission in the log
    entry = next((e for e in audit_log if e["content_id"] == content_id), None)

    if not entry:
        return jsonify({"error": "Content ID not found"}), 404

    # Update status and log appeal
    entry["status"] = "under_review"
    entry["appeal"] = {
        "creator_reasoning": creator_reasoning,
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }

    return jsonify({
        "message": "Your appeal has been received and is under review.",
        "content_id": content_id,
        "status": "under_review"
    })

@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": audit_log})

if __name__ == "__main__":
    app.run(debug=True)