import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def classify_with_llm(text: str) -> float:
    """
    Sends text to Groq and returns a score between 0 and 1.
    1.0 = very likely AI generated
    0.0 = very likely human written
    """
    prompt = f"""You are an AI detection expert. Analyze the following text and determine 
whether it was written by a human or generated by AI.

Return ONLY a JSON object in this exact format:
{{"score": 0.85, "reasoning": "one sentence explanation"}}

Where score is between 0 and 1:
- 1.0 means definitely AI generated
- 0.0 means definitely human written
- 0.5 means uncertain

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        response_format={"type": "json_object"}
    )
    
    result = response.choices[0].message.content
    import json
    parsed = json.loads(result)
    return float(parsed["score"])